/// Palestine and Israel cities list (alphabetically sorted)
const List<String> citiesList = [
  'Abu Dis',
  'Acre',
  'Afula',
  'Arad',
  'Ariel',
  'Ashdod',
  'Ashkelon',
  'Baqa al-Gharbiyye',
  'Bat Yam',
  'Beersheba',
  'Beit Shean',
  'Beit Shemesh',
  'Bethlehem',
  'Bnei Brak',
  'Dayr al-Balah',
  'Dimona',
  'Eilat',
  'Elad',
  'Gaza City',
  'Givatayim',
  'Hadera',
  'Haifa',
  'Hebron',
  'Herzliya',
  'Holon',
  'Jenin',
  'Jericho',
  'Jerusalem',
  'Kafr Qasim',
  'Khan Yunis',
  'Kiryat Ata',
  'Kiryat Bialik',
  'Kiryat Gat',
  'Kiryat Malakhi',
  'Kiryat Motzkin',
  'Kiryat Shmona',
  'Kiryat Yam',
  'Lod',
  'Maale Adumim',
  'Modiin',
  'Nablus',
  'Nahariya',
  'Nazareth',
  'Netanya',
  'Netivot',
  'Ofakim',
  'Qalqilyah',
  'Rafah',
  'Rahat',
  'Ramallah',
  'Ramla',
  "Ra'anana",
  'Rehovot',
  'Rishon LeZion',
  'Safed',
  'Sderot',
  'Tayibe',
  'Tel Aviv',
  'Tiberias',
  'Tulkarm',
  'Umm al-Fahm',
  'West Jerusalem',
  'Yavne',
  'Yehud',
  "Zikhron Ya'akov",
];
